services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./front:/usr/share/nginx/html
    networks:
      - tp1-network

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - 8080:8080
    networks:
      - tp1-network
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/demo-realm || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  tp1-network:
    driver: bridge