/**
 * API Réservation de Vols
 * Web service REST de réservation de vols sécurisé par Keycloak (JWT Bearer)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VolsApi);
  }
}(this, function(expect, VolsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VolsApi.Vol();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Vol', function() {
    it('should create an instance of Vol', function() {
      // uncomment below and update the code to test Vol
      //var instance = new VolsApi.Vol();
      //expect(instance).to.be.a(VolsApi.Vol);
    });

    it('should have the property compagnieAerienne (base name: "compagnieAerienne")', function() {
      // uncomment below and update the code to test the property compagnieAerienne
      //var instance = new VolsApi.Vol();
      //expect(instance).to.be();
    });

    it('should have the property numeroVol (base name: "numeroVol")', function() {
      // uncomment below and update the code to test the property numeroVol
      //var instance = new VolsApi.Vol();
      //expect(instance).to.be();
    });

    it('should have the property place (base name: "place")', function() {
      // uncomment below and update the code to test the property place
      //var instance = new VolsApi.Vol();
      //expect(instance).to.be();
    });

    it('should have the property prix (base name: "prix")', function() {
      // uncomment below and update the code to test the property prix
      //var instance = new VolsApi.Vol();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new VolsApi.Vol();
      //expect(instance).to.be();
    });

  });

}));
