/**
 * API Réservation de Vols
 * Web service REST de réservation de vols sécurisé par Keycloak (JWT Bearer)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Vol model module.
 * @module model/Vol
 * @version 1.0.0
 */
class Vol {
    /**
     * Constructs a new <code>Vol</code>.
     * @alias module:model/Vol
     * @param compagnieAerienne {String} 
     * @param numeroVol {String} 
     * @param place {String} 
     * @param prix {Number} 
     * @param date {Date} 
     */
    constructor(compagnieAerienne, numeroVol, place, prix, date) { 
        
        Vol.initialize(this, compagnieAerienne, numeroVol, place, prix, date);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, compagnieAerienne, numeroVol, place, prix, date) { 
        obj['compagnieAerienne'] = compagnieAerienne;
        obj['numeroVol'] = numeroVol;
        obj['place'] = place;
        obj['prix'] = prix;
        obj['date'] = date;
    }

    /**
     * Constructs a <code>Vol</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Vol} obj Optional instance to populate.
     * @return {module:model/Vol} The populated <code>Vol</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Vol();

            if (data.hasOwnProperty('compagnieAerienne')) {
                obj['compagnieAerienne'] = ApiClient.convertToType(data['compagnieAerienne'], 'String');
            }
            if (data.hasOwnProperty('numeroVol')) {
                obj['numeroVol'] = ApiClient.convertToType(data['numeroVol'], 'String');
            }
            if (data.hasOwnProperty('place')) {
                obj['place'] = ApiClient.convertToType(data['place'], 'String');
            }
            if (data.hasOwnProperty('prix')) {
                obj['prix'] = ApiClient.convertToType(data['prix'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Vol</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Vol</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Vol.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['compagnieAerienne'] && !(typeof data['compagnieAerienne'] === 'string' || data['compagnieAerienne'] instanceof String)) {
            throw new Error("Expected the field `compagnieAerienne` to be a primitive type in the JSON string but got " + data['compagnieAerienne']);
        }
        // ensure the json data is a string
        if (data['numeroVol'] && !(typeof data['numeroVol'] === 'string' || data['numeroVol'] instanceof String)) {
            throw new Error("Expected the field `numeroVol` to be a primitive type in the JSON string but got " + data['numeroVol']);
        }
        // ensure the json data is a string
        if (data['place'] && !(typeof data['place'] === 'string' || data['place'] instanceof String)) {
            throw new Error("Expected the field `place` to be a primitive type in the JSON string but got " + data['place']);
        }

        return true;
    }


}

Vol.RequiredProperties = ["compagnieAerienne", "numeroVol", "place", "prix", "date"];

/**
 * @member {String} compagnieAerienne
 */
Vol.prototype['compagnieAerienne'] = undefined;

/**
 * @member {String} numeroVol
 */
Vol.prototype['numeroVol'] = undefined;

/**
 * @member {String} place
 */
Vol.prototype['place'] = undefined;

/**
 * @member {Number} prix
 */
Vol.prototype['prix'] = undefined;

/**
 * @member {Date} date
 */
Vol.prototype['date'] = undefined;






export default Vol;

