/**
 * API Réservation de Vols
 * Web service REST de réservation de vols sécurisé par Keycloak (JWT Bearer)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Profil from '../model/Profil';
import Vol from '../model/Vol';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Profil de l'utilisateur connecté
     * Retourne les informations de l'utilisateur extraites du JWT Keycloak.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Profil} and HTTP response
     */
    getProfilWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Profil;
      return this.apiClient.callApi(
        '/profil', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Profil de l'utilisateur connecté
     * Retourne les informations de l'utilisateur extraites du JWT Keycloak.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Profil}
     */
    getProfil() {
      return this.getProfilWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Liste des vols disponibles
     * Retourne la liste statique des vols. JWT Keycloak requis.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Vol>} and HTTP response
     */
    getVolsWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Vol];
      return this.apiClient.callApi(
        '/vol', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Liste des vols disponibles
     * Retourne la liste statique des vols. JWT Keycloak requis.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Vol>}
     */
    getVols() {
      return this.getVolsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
